spring:
    profiles:
        active: dev
    h2:
        console:
            enabled: true
    datasource:
            dataSourceClassName: org.h2.jdbcx.JdbcDataSource
            url: jdbc:h2:mem:saleman;DB_CLOSE_DELAY=-1
            databaseName:
            serverName:
            username:
            password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    liquibase:
        change-log: classpath:/db/db.changelog-master.yaml
jwt:
    secret: amelas
    expiration: 80000
    header: token